### PR TITLE
Upgrade AdminLTE 2.4.3

### PR DESCRIPTION
**Pull request by siemensikkema**
Previous version was 2.3.11 from January 2017. Note to reviewers: please test in an existing project before approving to make sure everything works as expected.

### CODE REVIEW

**Comment by siemensikkema** [comment]
@MartinLasek @steffendsommer @BrettRToomey So far this has been working for me. Let's aim to get this merged soon and create a new minor version. Then we can use another minor version for the upcoming generic user update.

**Comment by steffendsommer** [comment]
@siemensikkema Is this a pure frontend dependency update? Does it change anything related to the workflow (which we need to mention in the readme)?

**Comment by siemensikkema** [comment]
@steffendsommer it is pure frontend and as it is, there are no changes required. Ideally we'd change it into the flow I'm using for my current project where I separate the files in Public and Private. We could also remove all the node_modules and makes this much more light weight. I already wrote the steps to 
do this:

---

# Common

# install nodes_modules and bower_components
cd [PROJECT]/Private && npm install && bower install

# AdminLTE

# Make any changes to AdminLTE related less or js and then:
grunt css js && cd [PROJECT] && cp Private/dist/css/AdminLTE.min.css Public/css && css Private/dist/js/adminlte.min.js Public/js

# Bootstrap

# install nodes_modules and bower_components
cd [PROJECT]/Private/bower_components/bootstrap && npm install && bower install

# Make any changes to bootstrap and then:
grunt prep-release —force

**Review by steffendsommer — APPROVED** [review]

**Comment by steffendsommer** [comment]
@siemensikkema considering the upcoming Vapor 3 update, I'm fine with staying MVP and merging this as a pure frontend update without changes in the workflow.

**Comment by siemensikkema** [comment]
@steffendsommer does this even require a new minor version?

**Pull request merged**
